#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/services.yaml
forum:
    path: /forum
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'forum/forum.html.twig'
